# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aSleaZynUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 819)
        MainWindow.setStyleSheet("font:11pt \"Comic Sans MS\";\n"
"color: rgb(100, 0, 50);\n"
"background-color: rgb(120, 210, 188);\n"
"border-color: rgb(130, 250, 230);\n"
"selection-background-color: rgb(210, 0, 210);\n"
"border-style: double;\n"
"border-width: 2px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnRenderTrack = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenderTrack.setGeometry(QtCore.QRect(280, 500, 111, 51))
        self.btnRenderTrack.setObjectName("btnRenderTrack")
        self.trackList = QtWidgets.QListView(self.centralwidget)
        self.trackList.setGeometry(QtCore.QRect(10, 80, 261, 261))
        self.trackList.setStyleSheet("")
        self.trackList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.trackList.setObjectName("trackList")
        self.btnTrackClone = QtWidgets.QPushButton(self.centralwidget)
        self.btnTrackClone.setGeometry(QtCore.QRect(10, 340, 61, 31))
        self.btnTrackClone.setObjectName("btnTrackClone")
        self.btnTrackDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnTrackDelete.setGeometry(QtCore.QRect(70, 340, 61, 31))
        self.btnTrackDelete.setObjectName("btnTrackDelete")
        self.btnRenderModule = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenderModule.setGeometry(QtCore.QRect(280, 450, 111, 51))
        self.btnRenderModule.setObjectName("btnRenderModule")
        self.btnRenderSong = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenderSong.setGeometry(QtCore.QRect(280, 550, 111, 51))
        self.btnRenderSong.setObjectName("btnRenderSong")
        self.spinTrackVolume = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinTrackVolume.setGeometry(QtCore.QRect(473, 80, 61, 33))
        self.spinTrackVolume.setDecimals(0)
        self.spinTrackVolume.setMaximum(999.0)
        self.spinTrackVolume.setSingleStep(1.0)
        self.spinTrackVolume.setObjectName("spinTrackVolume")
        self.editTrackName = QtWidgets.QLineEdit(self.centralwidget)
        self.editTrackName.setGeometry(QtCore.QRect(310, 80, 161, 31))
        self.editTrackName.setObjectName("editTrackName")
        self.moduleList = QtWidgets.QListView(self.centralwidget)
        self.moduleList.setGeometry(QtCore.QRect(540, 120, 251, 221))
        self.moduleList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.moduleList.setObjectName("moduleList")
        self.noteList = QtWidgets.QListView(self.centralwidget)
        self.noteList.setGeometry(QtCore.QRect(810, 120, 301, 221))
        self.noteList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.noteList.setObjectName("noteList")
        self.codeEditor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.codeEditor.setGeometry(QtCore.QRect(400, 430, 711, 341))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.codeEditor.sizePolicy().hasHeightForWidth())
        self.codeEditor.setSizePolicy(sizePolicy)
        self.codeEditor.setStyleSheet("font: 75 9pt \"Monospace\";")
        self.codeEditor.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.codeEditor.setReadOnly(True)
        self.codeEditor.setTabStopWidth(12)
        self.codeEditor.setBackgroundVisible(False)
        self.codeEditor.setObjectName("codeEditor")
        self.labelTracks = QtWidgets.QLabel(self.centralwidget)
        self.labelTracks.setGeometry(QtCore.QRect(10, 60, 60, 19))
        self.labelTracks.setStyleSheet("border: none;")
        self.labelTracks.setObjectName("labelTracks")
        self.labelTrackPars = QtWidgets.QLabel(self.centralwidget)
        self.labelTrackPars.setGeometry(QtCore.QRect(280, 60, 261, 19))
        self.labelTrackPars.setStyleSheet("border: none;")
        self.labelTrackPars.setObjectName("labelTrackPars")
        self.labelTrackMods = QtWidgets.QLabel(self.centralwidget)
        self.labelTrackMods.setGeometry(QtCore.QRect(540, 60, 261, 19))
        self.labelTrackMods.setStyleSheet("border: none;")
        self.labelTrackMods.setObjectName("labelTrackMods")
        self.labelPatternNotes = QtWidgets.QLabel(self.centralwidget)
        self.labelPatternNotes.setGeometry(QtCore.QRect(810, 60, 261, 19))
        self.labelPatternNotes.setStyleSheet("border: none;")
        self.labelPatternNotes.setObjectName("labelPatternNotes")
        self.patternCombox = QtWidgets.QComboBox(self.centralwidget)
        self.patternCombox.setGeometry(QtCore.QRect(850, 80, 261, 31))
        self.patternCombox.setObjectName("patternCombox")
        self.btnApplyPattern = QtWidgets.QPushButton(self.centralwidget)
        self.btnApplyPattern.setGeometry(QtCore.QRect(810, 80, 41, 31))
        self.btnApplyPattern.setObjectName("btnApplyPattern")
        self.editBPM = QtWidgets.QLineEdit(self.centralwidget)
        self.editBPM.setGeometry(QtCore.QRect(360, 390, 231, 31))
        self.editBPM.setObjectName("editBPM")
        self.btnRandomSynth = QtWidgets.QPushButton(self.centralwidget)
        self.btnRandomSynth.setGeometry(QtCore.QRect(280, 340, 81, 41))
        self.btnRandomSynth.setObjectName("btnRandomSynth")
        self.btnRandomizeSynth = QtWidgets.QPushButton(self.centralwidget)
        self.btnRandomizeSynth.setGeometry(QtCore.QRect(360, 340, 91, 41))
        self.btnRandomizeSynth.setObjectName("btnRandomizeSynth")
        self.btnSaveSynth = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveSynth.setGeometry(QtCore.QRect(450, 340, 81, 41))
        self.btnSaveSynth.setObjectName("btnSaveSynth")
        self.spinModOn = QtWidgets.QSpinBox(self.centralwidget)
        self.spinModOn.setGeometry(QtCore.QRect(540, 80, 101, 33))
        self.spinModOn.setMaximum(999)
        self.spinModOn.setObjectName("spinModOn")
        self.spinModTranspose = QtWidgets.QSpinBox(self.centralwidget)
        self.spinModTranspose.setGeometry(QtCore.QRect(660, 80, 131, 33))
        self.spinModTranspose.setMinimum(-96)
        self.spinModTranspose.setMaximum(96)
        self.spinModTranspose.setSingleStep(12)
        self.spinModTranspose.setObjectName("spinModTranspose")
        self.editNote = QtWidgets.QLineEdit(self.centralwidget)
        self.editNote.setGeometry(QtCore.QRect(810, 340, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editNote.setFont(font)
        self.editNote.setObjectName("editNote")
        self.btnApplyNote = QtWidgets.QPushButton(self.centralwidget)
        self.btnApplyNote.setGeometry(QtCore.QRect(1080, 340, 31, 31))
        self.btnApplyNote.setObjectName("btnApplyNote")
        self.checkAutoReimport = QtWidgets.QCheckBox(self.centralwidget)
        self.checkAutoReimport.setGeometry(QtCore.QRect(620, 10, 251, 21))
        self.checkAutoReimport.setStyleSheet("border: none;")
        self.checkAutoReimport.setObjectName("checkAutoReimport")
        self.editFilename = QtWidgets.QLineEdit(self.centralwidget)
        self.editFilename.setGeometry(QtCore.QRect(50, 10, 451, 41))
        self.editFilename.setObjectName("editFilename")
        self.btnImport = QtWidgets.QPushButton(self.centralwidget)
        self.btnImport.setGeometry(QtCore.QRect(510, 10, 101, 41))
        self.btnImport.setObjectName("btnImport")
        self.btnChooseFilename = QtWidgets.QPushButton(self.centralwidget)
        self.btnChooseFilename.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.btnChooseFilename.setObjectName("btnChooseFilename")
        self.checkTrackMute = QtWidgets.QCheckBox(self.centralwidget)
        self.checkTrackMute.setGeometry(QtCore.QRect(280, 80, 31, 31))
        self.checkTrackMute.setStyleSheet("border: none;")
        self.checkTrackMute.setText("")
        self.checkTrackMute.setObjectName("checkTrackMute")
        self.drumList = QtWidgets.QListView(self.centralwidget)
        self.drumList.setGeometry(QtCore.QRect(10, 400, 261, 371))
        self.drumList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.drumList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.drumList.setObjectName("drumList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 380, 60, 21))
        self.label.setStyleSheet("border: none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 110, 71, 21))
        self.label_2.setStyleSheet("border: none;")
        self.label_2.setObjectName("label_2")
        self.synthList = QtWidgets.QListView(self.centralwidget)
        self.synthList.setGeometry(QtCore.QRect(280, 130, 251, 211))
        self.synthList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.synthList.setObjectName("synthList")
        self.btnExport = QtWidgets.QPushButton(self.centralwidget)
        self.btnExport.setGeometry(QtCore.QRect(870, 10, 241, 41))
        self.btnExport.setObjectName("btnExport")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 420, 111, 31))
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setObjectName("label_3")
        self.btnStopPlayback = QtWidgets.QPushButton(self.centralwidget)
        self.btnStopPlayback.setGeometry(QtCore.QRect(280, 700, 111, 71))
        self.btnStopPlayback.setObjectName("btnStopPlayback")
        self.spinBStop = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBStop.setGeometry(QtCore.QRect(280, 630, 111, 33))
        self.spinBStop.setDecimals(1)
        self.spinBStop.setMaximum(999.0)
        self.spinBStop.setObjectName("spinBStop")
        self.spinBOffset = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBOffset.setGeometry(QtCore.QRect(280, 600, 111, 33))
        self.spinBOffset.setDecimals(1)
        self.spinBOffset.setMaximum(999.0)
        self.spinBOffset.setObjectName("spinBOffset")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 390, 81, 31))
        self.label_4.setStyleSheet("border: none;")
        self.label_4.setObjectName("label_4")
        self.editSynthName = QtWidgets.QLineEdit(self.centralwidget)
        self.editSynthName.setGeometry(QtCore.QRect(530, 350, 201, 31))
        self.editSynthName.setObjectName("editSynthName")
        self.btnApplySynthName = QtWidgets.QPushButton(self.centralwidget)
        self.btnApplySynthName.setGeometry(QtCore.QRect(730, 350, 51, 31))
        self.btnApplySynthName.setObjectName("btnApplySynthName")
        self.btnReloadSyn = QtWidgets.QPushButton(self.centralwidget)
        self.btnReloadSyn.setGeometry(QtCore.QRect(140, 350, 131, 41))
        self.btnReloadSyn.setObjectName("btnReloadSyn")
        self.checkWriteWAV = QtWidgets.QCheckBox(self.centralwidget)
        self.checkWriteWAV.setGeometry(QtCore.QRect(280, 670, 111, 23))
        self.checkWriteWAV.setObjectName("checkWriteWAV")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(600, 390, 51, 31))
        self.label_6.setStyleSheet("border: none;")
        self.label_6.setObjectName("label_6")
        self.spinLevelSyn = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinLevelSyn.setGeometry(QtCore.QRect(650, 390, 91, 33))
        self.spinLevelSyn.setSuffix("")
        self.spinLevelSyn.setDecimals(3)
        self.spinLevelSyn.setMaximum(9.99)
        self.spinLevelSyn.setSingleStep(0.05)
        self.spinLevelSyn.setObjectName("spinLevelSyn")
        self.spinLevelDrum = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinLevelDrum.setGeometry(QtCore.QRect(740, 390, 91, 33))
        self.spinLevelDrum.setDecimals(3)
        self.spinLevelDrum.setMaximum(9.99)
        self.spinLevelDrum.setSingleStep(0.05)
        self.spinLevelDrum.setObjectName("spinLevelDrum")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(940, 390, 71, 31))
        self.label_7.setStyleSheet("border: none;")
        self.label_7.setObjectName("label_7")
        self.spinTimeShift = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinTimeShift.setGeometry(QtCore.QRect(1020, 390, 91, 33))
        self.spinTimeShift.setPrefix("")
        self.spinTimeShift.setDecimals(2)
        self.spinTimeShift.setMaximum(999.99)
        self.spinTimeShift.setSingleStep(1.0)
        self.spinTimeShift.setObjectName("spinTimeShift")
        self.checkAutoRender = QtWidgets.QCheckBox(self.centralwidget)
        self.checkAutoRender.setGeometry(QtCore.QRect(620, 30, 221, 21))
        self.checkAutoRender.setStyleSheet("border: none;")
        self.checkAutoRender.setObjectName("checkAutoRender")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 38))
        self.menubar.setObjectName("menubar")
        self.menuThis_is_sleazy_crap = QtWidgets.QMenu(self.menubar)
        self.menuThis_is_sleazy_crap.setObjectName("menuThis_is_sleazy_crap")
        MainWindow.setMenuBar(self.menubar)
        self.actionVerstehe_ich = QtWidgets.QAction(MainWindow)
        self.actionVerstehe_ich.setObjectName("actionVerstehe_ich")
        self.menuThis_is_sleazy_crap.addAction(self.actionVerstehe_ich)
        self.menubar.addAction(self.menuThis_is_sleazy_crap.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "aSleeeeeaZyn..th"))
        self.btnRenderTrack.setText(_translate("MainWindow", "Track >>"))
        self.btnTrackClone.setText(_translate("MainWindow", "Clone"))
        self.btnTrackDelete.setText(_translate("MainWindow", "—"))
        self.btnRenderModule.setText(_translate("MainWindow", "Mod >>"))
        self.btnRenderSong.setText(_translate("MainWindow", "Song >>"))
        self.spinTrackVolume.setToolTip(_translate("MainWindow", "<html><head/><body><p>Track Volume</p></body></html>"))
        self.spinTrackVolume.setSuffix(_translate("MainWindow", "%"))
        self.editTrackName.setToolTip(_translate("MainWindow", "<html><head/><body><p>Track Name</p></body></html>"))
        self.labelTracks.setText(_translate("MainWindow", "Tracks"))
        self.labelTrackPars.setText(_translate("MainWindow", "Track Parameters / Synths"))
        self.labelTrackMods.setText(_translate("MainWindow", "Track Modules"))
        self.labelPatternNotes.setText(_translate("MainWindow", "Pattern / Notes"))
        self.btnApplyPattern.setText(_translate("MainWindow", "<--"))
        self.editBPM.setToolTip(_translate("MainWindow", "<html><head/><body><p>BPM</p></body></html>"))
        self.btnRandomSynth.setText(_translate("MainWindow", "Rnd Syn"))
        self.btnRandomizeSynth.setText(_translate("MainWindow", "Throw Rnds"))
        self.btnSaveSynth.setText(_translate("MainWindow", "Save This"))
        self.spinModOn.setToolTip(_translate("MainWindow", "<html><head/><body><p>modOn</p></body></html>"))
        self.spinModOn.setPrefix(_translate("MainWindow", "@ "))
        self.spinModTranspose.setPrefix(_translate("MainWindow", "transpose: "))
        self.editNote.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">pitch [on, off] (vel, pan, slide, aux)</span></p></body></html>"))
        self.editNote.setPlaceholderText(_translate("MainWindow", "pitch [on, off] (vel, pan, slide, aux)"))
        self.btnApplyNote.setText(_translate("MainWindow", "^^"))
        self.checkAutoReimport.setText(_translate("MainWindow", "Auto Re-Import On File Change"))
        self.btnImport.setText(_translate("MainWindow", "Re-Import"))
        self.btnChooseFilename.setText(_translate("MainWindow", "..."))
        self.checkTrackMute.setToolTip(_translate("MainWindow", "<html><head/><body><p>Unmuted?</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Drums"))
        self.label_2.setText(_translate("MainWindow", "Sympfs"))
        self.btnExport.setText(_translate("MainWindow", "Export with Current Changes"))
        self.label_3.setText(_translate("MainWindow", "Shady Code:"))
        self.btnStopPlayback.setText(_translate("MainWindow", "PÄÄTY,\n"
"JUMALAUTA\n"
"PERKELE!"))
        self.spinBStop.setPrefix(_translate("MainWindow", "to "))
        self.spinBOffset.setPrefix(_translate("MainWindow", "from "))
        self.label_4.setText(_translate("MainWindow", "BPM array:"))
        self.editSynthName.setPlaceholderText(_translate("MainWindow", "Change Synth Name"))
        self.btnApplySynthName.setText(_translate("MainWindow", "apply"))
        self.btnReloadSyn.setText(_translate("MainWindow", "Reload .Syn"))
        self.checkWriteWAV.setText(_translate("MainWindow", "write .WAV"))
        self.label_6.setText(_translate("MainWindow", "levels:"))
        self.spinLevelSyn.setPrefix(_translate("MainWindow", "S "))
        self.spinLevelDrum.setPrefix(_translate("MainWindow", "D "))
        self.label_7.setText(_translate("MainWindow", "timeshift:"))
        self.spinTimeShift.setSuffix(_translate("MainWindow", " s"))
        self.checkAutoRender.setText(_translate("MainWindow", "Auto Render On Re-Import"))
        self.menuThis_is_sleazy_crap.setTitle(_translate("MainWindow", "This is sleazy crap, but its sound is aMaySyn!"))
        self.actionVerstehe_ich.setText(_translate("MainWindow", "I fully understand"))
