# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aSleaZynUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 819)
        MainWindow.setStyleSheet("font:11pt \"Comic Sans MS\";\n"
"color: rgb(100, 0, 50);\n"
"background-color: rgb(120, 210, 188);\n"
"border-color: rgb(130, 250, 230);\n"
"selection-background-color: rgb(210, 0, 210);\n"
"border-style: double;\n"
"border-width: 2px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnRenderTrack = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenderTrack.setGeometry(QtCore.QRect(350, 520, 71, 51))
        self.btnRenderTrack.setObjectName("btnRenderTrack")
        self.trackList = QtWidgets.QListView(self.centralwidget)
        self.trackList.setGeometry(QtCore.QRect(10, 70, 261, 261))
        self.trackList.setStyleSheet("")
        self.trackList.setObjectName("trackList")
        self.btnTrackAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnTrackAdd.setGeometry(QtCore.QRect(10, 330, 41, 31))
        self.btnTrackAdd.setObjectName("btnTrackAdd")
        self.btnTrackClone = QtWidgets.QPushButton(self.centralwidget)
        self.btnTrackClone.setGeometry(QtCore.QRect(50, 330, 41, 31))
        self.btnTrackClone.setObjectName("btnTrackClone")
        self.btnTrackDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnTrackDelete.setGeometry(QtCore.QRect(90, 330, 41, 31))
        self.btnTrackDelete.setObjectName("btnTrackDelete")
        self.btnRenderModule = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenderModule.setGeometry(QtCore.QRect(350, 470, 71, 51))
        self.btnRenderModule.setObjectName("btnRenderModule")
        self.btnRenderSong = QtWidgets.QPushButton(self.centralwidget)
        self.btnRenderSong.setGeometry(QtCore.QRect(350, 570, 71, 51))
        self.btnRenderSong.setObjectName("btnRenderSong")
        self.spinTrackVolume = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinTrackVolume.setGeometry(QtCore.QRect(463, 70, 81, 33))
        self.spinTrackVolume.setDecimals(1)
        self.spinTrackVolume.setMaximum(200.0)
        self.spinTrackVolume.setSingleStep(1.0)
        self.spinTrackVolume.setObjectName("spinTrackVolume")
        self.editTrackName = QtWidgets.QLineEdit(self.centralwidget)
        self.editTrackName.setGeometry(QtCore.QRect(310, 70, 151, 33))
        self.editTrackName.setObjectName("editTrackName")
        self.moduleList = QtWidgets.QListView(self.centralwidget)
        self.moduleList.setGeometry(QtCore.QRect(550, 110, 261, 221))
        self.moduleList.setObjectName("moduleList")
        self.noteList = QtWidgets.QListView(self.centralwidget)
        self.noteList.setGeometry(QtCore.QRect(820, 110, 261, 221))
        self.noteList.setObjectName("noteList")
        self.codeEditor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.codeEditor.setGeometry(QtCore.QRect(430, 410, 651, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.codeEditor.sizePolicy().hasHeightForWidth())
        self.codeEditor.setSizePolicy(sizePolicy)
        self.codeEditor.setStyleSheet("font: 75 9pt \"Monospace\";")
        self.codeEditor.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.codeEditor.setReadOnly(True)
        self.codeEditor.setTabStopWidth(12)
        self.codeEditor.setBackgroundVisible(False)
        self.codeEditor.setObjectName("codeEditor")
        self.labelTracks = QtWidgets.QLabel(self.centralwidget)
        self.labelTracks.setGeometry(QtCore.QRect(10, 50, 60, 19))
        self.labelTracks.setObjectName("labelTracks")
        self.labelTrackPars = QtWidgets.QLabel(self.centralwidget)
        self.labelTrackPars.setGeometry(QtCore.QRect(280, 50, 261, 19))
        self.labelTrackPars.setObjectName("labelTrackPars")
        self.labelTrackMods = QtWidgets.QLabel(self.centralwidget)
        self.labelTrackMods.setGeometry(QtCore.QRect(550, 50, 261, 19))
        self.labelTrackMods.setObjectName("labelTrackMods")
        self.labelPatternNotes = QtWidgets.QLabel(self.centralwidget)
        self.labelPatternNotes.setGeometry(QtCore.QRect(820, 50, 261, 19))
        self.labelPatternNotes.setObjectName("labelPatternNotes")
        self.patternCombox = QtWidgets.QComboBox(self.centralwidget)
        self.patternCombox.setGeometry(QtCore.QRect(860, 70, 221, 31))
        self.patternCombox.setObjectName("patternCombox")
        self.btnApplyPattern = QtWidgets.QPushButton(self.centralwidget)
        self.btnApplyPattern.setGeometry(QtCore.QRect(820, 70, 41, 31))
        self.btnApplyPattern.setObjectName("btnApplyPattern")
        self.editBPM = QtWidgets.QLineEdit(self.centralwidget)
        self.editBPM.setGeometry(QtCore.QRect(420, 380, 261, 33))
        self.editBPM.setObjectName("editBPM")
        self.btnRandomSynth = QtWidgets.QPushButton(self.centralwidget)
        self.btnRandomSynth.setGeometry(QtCore.QRect(280, 330, 81, 41))
        self.btnRandomSynth.setObjectName("btnRandomSynth")
        self.btnRandomizeSynth = QtWidgets.QPushButton(self.centralwidget)
        self.btnRandomizeSynth.setGeometry(QtCore.QRect(360, 330, 91, 41))
        self.btnRandomizeSynth.setObjectName("btnRandomizeSynth")
        self.btnSaveSynth = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveSynth.setGeometry(QtCore.QRect(450, 330, 91, 41))
        self.btnSaveSynth.setObjectName("btnSaveSynth")
        self.spinModOn = QtWidgets.QSpinBox(self.centralwidget)
        self.spinModOn.setGeometry(QtCore.QRect(550, 70, 84, 33))
        self.spinModOn.setObjectName("spinModOn")
        self.spinModTranspose = QtWidgets.QSpinBox(self.centralwidget)
        self.spinModTranspose.setGeometry(QtCore.QRect(683, 70, 131, 33))
        self.spinModTranspose.setMinimum(-96)
        self.spinModTranspose.setMaximum(96)
        self.spinModTranspose.setSingleStep(12)
        self.spinModTranspose.setObjectName("spinModTranspose")
        self.editNote = QtWidgets.QLineEdit(self.centralwidget)
        self.editNote.setGeometry(QtCore.QRect(820, 360, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.editNote.setFont(font)
        self.editNote.setObjectName("editNote")
        self.btnApplyNote = QtWidgets.QPushButton(self.centralwidget)
        self.btnApplyNote.setGeometry(QtCore.QRect(1030, 330, 51, 31))
        self.btnApplyNote.setObjectName("btnApplyNote")
        self.checkAutoRender = QtWidgets.QCheckBox(self.centralwidget)
        self.checkAutoRender.setGeometry(QtCore.QRect(600, 0, 201, 41))
        self.checkAutoRender.setObjectName("checkAutoRender")
        self.editFilename = QtWidgets.QLineEdit(self.centralwidget)
        self.editFilename.setGeometry(QtCore.QRect(140, 0, 451, 41))
        self.editFilename.setObjectName("editFilename")
        self.btnImport = QtWidgets.QPushButton(self.centralwidget)
        self.btnImport.setGeometry(QtCore.QRect(10, 0, 81, 41))
        self.btnImport.setObjectName("btnImport")
        self.btnChooseFilename = QtWidgets.QPushButton(self.centralwidget)
        self.btnChooseFilename.setGeometry(QtCore.QRect(100, 0, 41, 41))
        self.btnChooseFilename.setObjectName("btnChooseFilename")
        self.checkTrackMute = QtWidgets.QCheckBox(self.centralwidget)
        self.checkTrackMute.setGeometry(QtCore.QRect(280, 70, 31, 31))
        self.checkTrackMute.setText("")
        self.checkTrackMute.setObjectName("checkTrackMute")
        self.drumList = QtWidgets.QListView(self.centralwidget)
        self.drumList.setGeometry(QtCore.QRect(10, 390, 261, 371))
        self.drumList.setObjectName("drumList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 370, 60, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 100, 71, 31))
        self.label_2.setObjectName("label_2")
        self.synthList = QtWidgets.QListView(self.centralwidget)
        self.synthList.setGeometry(QtCore.QRect(280, 130, 261, 201))
        self.synthList.setObjectName("synthList")
        self.btnExport = QtWidgets.QPushButton(self.centralwidget)
        self.btnExport.setGeometry(QtCore.QRect(810, 0, 271, 41))
        self.btnExport.setObjectName("btnExport")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 420, 101, 31))
        self.label_3.setObjectName("label_3")
        self.btnStopPlayback = QtWidgets.QPushButton(self.centralwidget)
        self.btnStopPlayback.setGeometry(QtCore.QRect(290, 690, 131, 71))
        self.btnStopPlayback.setObjectName("btnStopPlayback")
        self.spinBStop = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBStop.setGeometry(QtCore.QRect(310, 650, 111, 33))
        self.spinBStop.setMaximum(999.0)
        self.spinBStop.setObjectName("spinBStop")
        self.spinBOffset = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBOffset.setGeometry(QtCore.QRect(310, 620, 111, 33))
        self.spinBOffset.setObjectName("spinBOffset")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 380, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(820, 330, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 330, 141, 31))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 38))
        self.menubar.setObjectName("menubar")
        self.menuThis_is_sleazy_crap = QtWidgets.QMenu(self.menubar)
        self.menuThis_is_sleazy_crap.setObjectName("menuThis_is_sleazy_crap")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.toolBar_4 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_4.setObjectName("toolBar_4")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_4)
        self.toolBar_5 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_5.setObjectName("toolBar_5")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_5)
        self.toolBar_6 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_6.setObjectName("toolBar_6")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_6)
        self.toolBar_7 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_7.setObjectName("toolBar_7")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_7)
        self.actionVerstehe_ich = QtWidgets.QAction(MainWindow)
        self.actionVerstehe_ich.setObjectName("actionVerstehe_ich")
        self.menuThis_is_sleazy_crap.addAction(self.actionVerstehe_ich)
        self.menubar.addAction(self.menuThis_is_sleazy_crap.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "aSleeeeeaZyn..th"))
        self.btnRenderTrack.setText(_translate("MainWindow", "Track >>"))
        self.btnTrackAdd.setText(_translate("MainWindow", "+"))
        self.btnTrackClone.setText(_translate("MainWindow", "C"))
        self.btnTrackDelete.setText(_translate("MainWindow", "--"))
        self.btnRenderModule.setText(_translate("MainWindow", "Mod >>"))
        self.btnRenderSong.setText(_translate("MainWindow", "Song >>"))
        self.spinTrackVolume.setToolTip(_translate("MainWindow", "<html><head/><body><p>Track Volume</p></body></html>"))
        self.spinTrackVolume.setSuffix(_translate("MainWindow", "%"))
        self.editTrackName.setToolTip(_translate("MainWindow", "<html><head/><body><p>Track Name</p></body></html>"))
        self.labelTracks.setText(_translate("MainWindow", "Tracks"))
        self.labelTrackPars.setText(_translate("MainWindow", "Track Parameters / Synths"))
        self.labelTrackMods.setText(_translate("MainWindow", "Track Modules"))
        self.labelPatternNotes.setText(_translate("MainWindow", "Pattern / Notes"))
        self.btnApplyPattern.setText(_translate("MainWindow", "<--"))
        self.editBPM.setToolTip(_translate("MainWindow", "<html><head/><body><p>BPM</p></body></html>"))
        self.btnRandomSynth.setText(_translate("MainWindow", "Rnd Syn"))
        self.btnRandomizeSynth.setText(_translate("MainWindow", "Throw Rnds"))
        self.btnSaveSynth.setText(_translate("MainWindow", "Save This"))
        self.spinModOn.setToolTip(_translate("MainWindow", "<html><head/><body><p>modOn</p></body></html>"))
        self.spinModOn.setPrefix(_translate("MainWindow", "@ "))
        self.spinModTranspose.setPrefix(_translate("MainWindow", "transpose: "))
        self.editNote.setToolTip(_translate("MainWindow", "<html><head/><body><p>Note Parameters or Pattern Command</p></body></html>"))
        self.btnApplyNote.setText(_translate("MainWindow", "^^"))
        self.checkAutoRender.setText(_translate("MainWindow", "Auto Render On Change"))
        self.btnImport.setText(_translate("MainWindow", "Import"))
        self.btnChooseFilename.setText(_translate("MainWindow", "..."))
        self.checkTrackMute.setToolTip(_translate("MainWindow", "<html><head/><body><p>Unmuted?</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Drums:"))
        self.label_2.setText(_translate("MainWindow", "Sympfs:"))
        self.btnExport.setText(_translate("MainWindow", "Export with Changes"))
        self.label_3.setText(_translate("MainWindow", "Shady Code:"))
        self.btnStopPlayback.setText(_translate("MainWindow", "PÄÄTY,\n"
"JUMALAUTA\n"
"PERKELE!"))
        self.spinBStop.setPrefix(_translate("MainWindow", "to "))
        self.spinBOffset.setPrefix(_translate("MainWindow", "from "))
        self.label_4.setText(_translate("MainWindow", "BPM array:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">pitch [on, off] (vel, pan, slide, aux)</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<- these do nothing"))
        self.menuThis_is_sleazy_crap.setTitle(_translate("MainWindow", "This is sleazy crap, but its sound is aMaySyn!"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.toolBar_4.setWindowTitle(_translate("MainWindow", "toolBar_4"))
        self.toolBar_5.setWindowTitle(_translate("MainWindow", "toolBar_5"))
        self.toolBar_6.setWindowTitle(_translate("MainWindow", "toolBar_6"))
        self.toolBar_7.setWindowTitle(_translate("MainWindow", "toolBar_7"))
        self.actionVerstehe_ich.setText(_translate("MainWindow", "I fully understand"))
